name: test-environment
channels:
  - conda-forge
dependencies:
  - sphinx
  - pillow
  - pyproj
  - coveralls
  - coverage
  - aggdraw
  - pyshp
  - pyresample
  - pytest <8.0
  - pytest-cov
  - pytest-lazy-fixture
